// Copyright 2023 Gustaw.xyz (@Gustaw.xyz)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0

#define MASTER_RIGHT

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U 

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_INVERT_Y
#define SPI_DRIVER SPID0
#define POINTING_DEVICE_RIGHT
//#define PMW33XX_CPI 1600
//#define PMW33XX_CLOCK_SPEED 2000000
#define MOUSE_EXTENDED_REPORT
//#define PMW33XX_LIFTOFF_DISTANCE 0x02

#define PMW33XX_CS_PIN GP17
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP16